name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Dependencies
        run: pnpm install
        # declare .env variables here
      - name: Check Formatting
        run: pnpm fmt
      - name: Run Linters
        run: pnpm lint
        # declare .env variables here
